config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users do
    resource :profile
  end
  root 'pages#home'
  get 'about' => 'pages#about'
  resources :charges
  resources :orders
  

end

app/models/car.rb
class Car < ActiveRecord::Base

end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base

	belongs_to :user
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def create

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => params[:amount],
    :description => 'Rails Stripe customer',
    :currency    => 'sgd'
  )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

app/controllers/orders_controller.rb
class OrdersController < ActionController::Base
	
	def new
	end

	def create
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   def home
   end 
   def about
   end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	
	def new
		# form for user to fill up own profile
		@user = User.find( params[:user_id] ) #determines logged in user
	  @profile = @user.build_profile
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/cars/_new_car.html.erb
<h1> Car details form </h1>

app/views/cars/new.html.erb
<!-- Create partial to add car details -->
<h1> Cars details here </h1>

app/views/charges/create.html.erb
<h1> Purchase Success </h1>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Polysh</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li> 
      <% if user_signed_in? %>
        <li><%= link_to "Update Profile", new_user_profile_path(current_user) if current_user %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, user-scalable=no">
  <title>Polysh</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300,800' >
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- Navigation links -->
	<%= render 'layouts/header' %>



	<div class = "container">	
		<!-- Flash Message -->
		<% flash.each do |name, msg| %>
	     <%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>

		<!-- Render Content -->
		<%= yield %>
	</div>

<!-- Scripts -->
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
</html>

app/views/locations/_new_loc.html.erb
<h1> Parking location form </h1>

app/views/locations/new.html.erb
<!-- create partial file for rendering location details -->

app/views/orders/new.html.erb
<div>
<h1>Order Here</h1>

<%= render 'cars/new_car' %>	

<%= render 'locations/new_loc' %>

<%= render 'profiles/new_prof' %>

<%= link_to "Book now", new_order_path, class: "btn btn-success btn-lg" %>
</div>

app/views/pages/about.html.erb
<h1>about</h1>


<% if user_signed_in? %>
    <p> Product to be subscribed </p>
<% end %>
<!-- Stripe Charging -->
<%= form_tag charges_path, id: 'chargeForm' do %>
	<script src="https://checkout.stripe.com/checkout.js"></script>
	<%= hidden_field_tag 'stripeToken' %>
	<%= hidden_field_tag 'stripeEmail' %> 
	<%= hidden_field_tag 'amount', 2000 %>
	<button id="customButton" class= "btn btn-success btn-lg btn-block">Purchase</button>

	<script>
	  var handler = StripeCheckout.configure({
	    key: '<%= Rails.configuration.stripe[:publishable_key] %>',
	    locale: 'auto',
	    token: function(token, arg) {
	        document.getElementById("stripeToken").value = token.id;
	        document.getElementById("stripeEmail").value = token.email;
	        document.getElementById("chargeForm").submit();
	      }
	  });

	   document.getElementById('customButton').addEventListener('click', function(e) {
	      handler.open({
	      name: 'Basic Package',
	      description: 'Basic Package S$20.00',
	      currency: "sgd",
	      amount: document.getElementById("amount").value 
	    });
	    e.preventDefault();
	  });

		// Close Checkout on page navigation
	  $(window).on('popstate', function() {
	    handler.close();
	  });
	</script>
<% end %>

app/views/pages/home.html.erb
<div class = "jumbotron">
  <h1>Home</h1>
  	<%= link_to "Check Availability", new_order_path, class: "btn btn-success btn-lg" %>
  

<!--   <% if user_signed_in? %>
    <p> Product to be subscribed </p>
  <% else %>  
    <p>
       <%= link_to "Sign Up Now", new_user_registration_path, class: "btn btn-success btn-lg" %>
     </p>
  <% end %> -->
</div>

app/views/profiles/_new_prof.html.erb
<h1> Profile form here </h1>

app/views/profiles/new.html.erb
<!-- Create a partial for rendering-->
test